// APP
export const APP_LOAD = 'APP_LOAD';
// AUTH
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REGISTER = 'AUTH_REGISTER';

// EQLAB
export const SUBAPP_UNLOAD = 'SUBAPP_UNLOAD';

// GLOBAL EDITORS
export const GLOBAL_RESET = 'GLOBAL_RESET';
// SPAWN EDITOR
export const GLOBAL_LOAD_SPAWNEDITOR = 'GLOBAL_LOAD_SPAWNEDITOR';
export const GLOBAL_UNLOAD_SPAWNEDITOR = 'GLOBAL_UNLOAD_SPAWNEDITOR';
export const GLOBAL_UPDATE_SPAWN2 = 'GLOBAL_UPDATE_SPAWN2';
export const GLOBAL_DELETE_SPAWN2 = 'GLOBAL_DELETE_SPAWN2';
export const GLOBAL_CHANGE_SPAWNGROUP = 'GLOBAL_CHANGE_SPAWNGROUP';
export const GLOBAL_POST_SPAWNGROUP = 'GLOBAL_POST_SPAWNGROUP';
export const GLOBAL_UPDATE_SPAWNGROUP = 'GLOBAL_UPDATE_SPAWNGROUP';
export const GLOBAL_DELETE_SPAWNGROUP = 'GLOBAL_DELETE_SPAWNGROUP';
export const GLOBAL_POST_SPAWNENTRY = 'GLOBAL_POST_SPAWNENTRY';
export const GLOBAL_DELETE_SPAWNENTRY = 'GLOBAL_DELETE_SPAWNENTRY';
// NPC EDITOR
export const GLOBAL_LOAD_NPC = 'GLOBAL_LOAD_NPC';
export const GLOBAL_UNLOAD_NPC = 'GLOBAL_UNLOAD_NPC';

// ZONE APP
export const ZONEAPP_RESET = 'ZONEAPP_RESET';
export const ZONEAPP_SELECT_ZONE = 'ZONEAPP_SELECT_ZONE';
export const ZONEAPP_SET_ZONE = 'ZONEAPP_SET_ZONE';
export const ZONEAPP_BUILD_SPAWNTREE = 'ZONEAPP_BUILD_SPAWNTREE';
export const ZONEAPP_CLEAR_SPAWNTREE = 'ZONEAPP_CLEAR_SPAWNTREE';
export const ZONEAPP_POST_SPAWN2 = 'ZONEAPP_POST_SPAWN2';
export const ZONEAPP_ADD_SPAWN2 = 'ZONEAPP_ADD_SPAWN2';
export const ZONEAPP_ADD_SPAWNGROUP = 'ZONEAPP_ADD_SPAWNGROUP';
export const ZONEAPP_ADD_SPAWNENTRY = 'ZONEAPP_ADD_SPAWNENTRY';
export const ZONEAPP_REMOVE_SPAWN2 = 'ZONEAPP_REMOVE_SPAWN2';
export const ZONEAPP_REMOVE_SPAWNGROUP = 'ZONEAPP_REMOVE_SPAWNGROUP';
export const ZONEAPP_REMOVE_SPAWNENTRY = 'ZONEAPP_REMOVE_SPAWNENTRY';
